
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
mqtt:
  sensor:
  - name: "Status"
    state_topic: "deye/status"
    unique_id: status
    qos: 0
    force_update: true
    icon: 'mdi:solar-power'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }    

  - name: "Radiator Temperature"
    state_topic: "deye/radiator_temp"
    unique_id: ac/radiator_temp
    qos: 0
    force_update: true
    unit_of_measurement: "°C"
    icon: 'mdi:solar-power'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "Produção de energia hoje"
    state_topic: "deye/day_energy"
    state_class: total
    device_class: energy
    unique_id: day_energy
    qos: 0
    force_update: true
    unit_of_measurement: "kWh"
    icon: 'mdi:solar-power'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "Produção de energia total"
    state_topic: "deye/total_energy"
    state_class: total
    device_class: energy
    unique_id: total_energy
    qos: 0
    force_update: true
    unit_of_measurement: "kWh"
    icon: 'mdi:solar-power'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "Operating Power"
    state_topic: "deye/operating_power"
    unique_id: operating_power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - Power"
    state_topic: "deye/ac/l1/power"
    state_class: total
    unique_id: ac/l1/power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - Aparent Power"
    state_topic: "deye/ac/apparent_power"
    unique_id: ac/apparent_power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - Active Power"
    state_topic: "deye/ac/active_power"
    unique_id: ac/active_power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - Reactive Power"
    state_topic: "deye/ac/reactive_power"
    unique_id: ac/reactive_power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - R(V)"
    state_topic: "deye/ac/l1/voltage"
    state_class: total
    unique_id: ac/l1/voltage
    qos: 0
    force_update: true
    unit_of_measurement: "V"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - R(A)"
    state_topic: "deye/ac/l1/current"
    state_class: total
    unique_id: ac/l1/current
    qos: 0
    force_update: true
    unit_of_measurement: "A"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "AC - Frequência"
    state_topic: "deye/ac/freq"
    state_class: total
    unique_id: ac/freq
    qos: 0
    force_update: true
    unit_of_measurement: "Hz"
    icon: 'mdi:solar-power'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - Power 1"
    state_topic: "deye/dc/pv1/power"
    state_class: total
    unique_id: dc/pv1/power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - PV1(V)"
    state_topic: "deye/dc/pv1/voltage"
    state_class: total
    unique_id: dc/pv1/voltage
    qos: 0
    force_update: true
    unit_of_measurement: "V"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - PV1(A)"
    state_topic: "deye/dc/pv1/current"
    state_class: total
    unique_id: dc/pv1/current
    qos: 0
    force_update: true
    unit_of_measurement: "A"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - Power 2"
    state_topic: "deye/dc/pv2/power"
    state_class: total
    unique_id: dc/pv2/power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - PV2(V)"
    state_topic: "deye/dc/pv2/voltage"
    state_class: total
    unique_id: dc/pv2/voltage
    qos: 0
    force_update: true
    unit_of_measurement: "V"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - PV2(A)"
    state_topic: "deye/dc/pv2/current"
    state_class: total
    unique_id: dc/pv2/current
    qos: 0
    force_update: true
    unit_of_measurement: "A"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }

  - name: "DC - Total Power"
    state_topic: "deye/dc/total_power"
    state_class: total
    unique_id: dc/total_power
    qos: 0
    force_update: true
    unit_of_measurement: "W"
    icon: 'mdi:home-lightning-bolt'
    device: {
      model: "DEYE SUN-4K-G",
      identifiers: ["9"],
      suggested_area: "Casa"
    }