
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
# sensor:
  # - platform: netdata
  #   host: "192.168.1.113"
  #   port: "19999"
  #   name: netdatahost
  #   # resources:
  #   #   system_load:
  #   #     data_group: system.load
  #   #     element: load15
  #   #   system_cpu_utilization:
  #   #     data_group: app.system_cpu_utilization
  #   #     element: system
  #   #   system_user_utilization:
  #   #     data_group: app.system_cpu_utilization
  #   #     element: user
  #   #   mem_available:
  #   #     data_group: mem.available
  #   #     element: MemAvailable
mqtt:
  - energia:
    items:
        state_topic: deye/day_energy
        resources:
          data_group: energy_production
          element: day_energy

        # ,"deye/total_energy"
        # ,"deye/ac/l1/voltage"
        # ,"deye/ac/l1/current"
        # ,"deye/ac/l1/power"
        # ,"deye/ac/l2/voltage"
        # ,"deye/ac/l2/current"
        # ,"deye/ac/l2/power"
        # ,"deye/ac/l3/voltage"
        # ,"deye/ac/l3/current"
        # ,"deye/ac/l3/power"
        # ,"deye/ac/freq"
        # ,"deye/uptime"
        # ,"deye/dc/pv1/voltage"
        # ,"deye/dc/pv1/current"
        # ,"deye/dc/pv1/power"
        # ,"deye/dc/pv2/voltage"
        # ,"deye/dc/pv2/current"
        # ,"deye/dc/pv2/power"
        # ,"deye/dc/pv3/voltage"
        # ,"deye/dc/pv3/current"
        # ,"deye/dc/pv3/power"
        # ,"deye/dc/pv4/voltage"
        # ,"deye/dc/pv4/current"
        # ,"deye/dc/pv4/power"
        # ,"deye/dc/total_power"
        # ,"deye/operating_power"
        # ,"deye/ac/apparent_power"
        # ,"deye/ac/active_power"
        # ,"deye/ac/reactive_power"
        # ,"deye/radiator_temp"
        # ,"deye/igbt_temp"