
requests:
  - start: 0x003C
    end:  0x0070
    mb_functioncode: 0x03

parameters:
 - group: solar
   items: 

    - name: "Total Production"
      class: "energy"
      state_class: "total_increasing"
      uom: "kWh"
      scale: 0.1
      rule: 3
      registers: [0x003F,0x0040]
      icon: 'mdi:solar-power'
      validation:
        min: 0.1 
        invalidate_all:

    - name: "Today Production"
      class: "energy"
      state_class: "total"
      uom: "kWh"
      scale: 0.1
      rule: 1
      registers: [0x003C]
      icon: 'mdi:solar-power'

    - name: "PV1 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x006D]
      icon: 'mdi:solar-power'

    - name: "PV1 Current"
      class: "current"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x006E]
      icon: 'mdi:solar-power'

    - name: "PV2 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x006F]
      icon: 'mdi:solar-power'

    - name: "PV2 Current"
      class: "current"
      state_class: "measurement"
      uom: "A"
      scale: 0.1
      rule: 1
      registers: [0x0070]
      icon: 'mdi:solar-power'

 - group: Grid
   items: 
    - name: "Grid 1 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x0049]
      icon: 'mdi:transmission-tower'

    - name: "Grid 1 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.1
      rule: 2
      registers: [0x004C]
      icon: 'mdi:home-lightning-bolt'

    - name: "Grid 2 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x004A]
      icon: 'mdi:transmission-tower'

    - name: "Grid 2 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.1
      rule: 2
      registers: [0x004D]
      icon: 'mdi:home-lightning-bolt'

    - name: "Grid 3 Voltage"
      class: "voltage"
      state_class: "measurement"
      uom: "V"
      scale: 0.1
      rule: 1
      registers: [0x004B]
      icon: 'mdi:transmission-tower'

    - name: "Grid 3 Current"
      class: "current"
      state_class: "measurement"      
      uom: "A"
      scale: 0.1
      rule: 2
      registers: [0x004E]
      icon: 'mdi:home-lightning-bolt'

    - name: "Grid Frequency"
      class: "frequency"
      state_class: "measurement"      
      uom: "Hz"
      scale: 0.01
      rule: 1
      registers: [0x004F]
      icon: 'mdi:home-lightning-bolt'

 - group: Inverter
   items: 
    # - name: "Running Status"
    #   class: ""
    #   state_class: ""      
    #   uom: ""
    #   scale: 1
    #   rule: 1
    #   registers: [0x003B]
    #   isstr: true
    #   lookup: 
    #   -  key: 0
    #      value: "Stand-by"
    #   -  key: 1
    #      value: "Self-checking"
    #   -  key: 2
    #      value: "Normal"
    #   -  key: 3
    #      value: "FAULT"
    #   icon: 'mdi:home-lightning-bolt'

    - name: "Operating Power"
      class: "power"
      state_class: "measurement"      
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x0050]
      icon: 'mdi:home-lightning-bolt'

    - name: "DC Total Power"
      class: "power"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x0052]
      icon: 'mdi:home-lightning-bolt'

    - name: "AC Apparent Power"
      class: "apparent_power"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x0054]
      icon: 'mdi:home-lightning-bolt'

    - name: "AC Active Power"
      class: "energy"
      state_class: "measurement"
      uom: "W"
      scale: 0.1
      rule: 3
      registers: [0x0056, 0x0057]
      icon: 'mdi:home-lightning-bolt'

    - name: "IGBT temperature"
      class: "reactive_power"
      state_class: "measurement"
      uom: "°C"
      rule: 3
      scale: 0.1
      registers: [0x005B]
      icon: 'mdi:home-lightning-bolt'
